add: 모듈화된 파이썬 파일
2024-PNU-SW-StudyGroup/Group-11 pull request #4
Opened 2024-11-20 11:59 UTC by soheean1370

# 🔨 작업 내용

- PyTorch 기반 리뷰 점수 예측 모듈화 작업 완료
- ReviewModel 클래스를 활용해 BERT 기반 모델 로드 및 예측 로직 개선
- 클린업 함수와 점수 예측 메서드 (clean_text, predict_score)로 재사용성을 강화

# 💬 추가 사항

- 프론트엔드에서 /find API 호출 시, 리뷰 점수 예측 관련 요청 및 응답 구조 변경 필요:
   - 요청 예시: 리뷰 텍스트를 포함한 JSON 데이터
   - 응답 예시: 예측된 점수 (predicted_score)
- 기존 로직과 통합 테스트 필요.
! review_model.py 파일을 백엔드 환경에서 적절히 경로 설정 후 호출 필요

2024-11-21 17:16 UTC, bluelemon61 requested changes
### 추가 코멘트
- 추가사항에 프론트엔드에서 API 호출시 응답 구조 변경 필요 항목은 Pytorch 모델이 비동기적으로 돌아가도록 백엔드가 설계해놓았기 때문에 그대로 둬도 괜찮을 것 같습니닷!

2024-11-21 17:16 UTC, bluelemon61 commented on ai_web_pytorch/review_model.py
> +    self.model = BertForSequenceClassification.from_pretrained(model_name, num_labels=num_labels)
Class 인수가 `model_labels`인데 Bert Classification에는 `num_labels`를 넘기고 있네여 🥲  선언되지 않은 변수 에러

2024-11-21 17:16 UTC, bluelemon61 commented on ai_web_pytorch/review_model.py
> +    self.tokenizer = BertTokenizer.from_pretrained(model_name)
대회때 학습된 모델이 'bert-base-uncased' 모델을 기반으로 전이학습 한 것 같은데 `model_name` 값을 다른걸로 바꿔도 괜찮은건가유? 백엔드 입장에서는 `model_name`을 인자로 넘겨주는 것 보다 해당 클래스 내부에서 model_name을 'bert-base-uncased' 고정 값으로 두는게 더 좋을 것 같습니닷!!

실제로 백엔드 입장에서 어떻게 두는게 더 좋을지 백엔드가 직접 판단해보는게 더 좋을것같네여
@sanghunii @JakeFRCSE

2024-11-21 17:46 UTC, bluelemon61 commented
모델 가중치 파일은 드라이브에 있나유?? 드라이브 권한을 링크 허용으로 바꿔주시면 very thanks

2024-11-21 18:30 UTC, bluelemon61 commented on ai_web_pytorch/review_model.py
> +    self.tokenizer = BertTokenizer.from_pretrained(model_name)
이거 다시 생각해보니 어쩌피 가중치 파일로 덮어쓸거라 아무 pre-trained 모델 가중치를 불러와도 상관 없긴 하네유

차라리 pretrained 모델을 불러오는 불필요한 파트를 줄이는게 어떨까 하는 생각도 해봤는데 BertConfig 선언이 너무 번거로워서 pre-trained 메소드 쓰는게 더 나을 것같다

백엔드가 편한쪽으로 갑시더

2024-11-23 01:30 UTC, sanghunii commented on ai_web_pytorch/review_model.py
> +    self.tokenizer = BertTokenizer.from_pretrained(model_name)
가져와서 쓰는 입장에서는 클래스 내부에서 고정 값으로 둬주시면 타이핑 할거 줄어들어서 조 더 편할거 같아요.  저는 준혁이형 의견 따르겠습니다.

2024-11-23 02:51 UTC, JakeFRCSE requested changes
Review on model class initialization from the back-end side's point of view.

2024-11-23 02:51 UTC, JakeFRCSE commented on ai_web_pytorch/review_model.py
> +    self.tokenizer = BertTokenizer.from_pretrained(model_name)
클래스 내부에서 고정할 것 없이 __init__함수를 다음과 같이 수정하면 됩니다.
model_name : str, model_path: str, model_labels: int =5 ->
model_name : str = "모델 이름", model_path: str = "추가 가중치 주소", model_labels: int =5
이렇게 하면 필요할 때 다른 모델로 바꿀 수 있고 굳이 안 바꿀거면 편하게 모델 불러올 수 있습니다.

추가적으로 Bert 구조상 사전학습 본체에 추가로 학습한 새로운 층을 얹는 구조라서 지금 사용한 코드는 모두 필요한 것으로 보입니다.

결론: 선언되지 않은 변수 에러 고치고 생성자 기본인자값 설정해주세요.

2024-11-29 05:15 UTC, bluelemon61 approved these changes
# good 👍

2024-11-30 13:19 UTC, JakeFRCSE reviewed
주석 변경 및 모델 가중치 파일 공유 요청

2024-11-30 13:19 UTC, JakeFRCSE commented on ai_web_pytorch/review_model.py
> +        model_path (str): 저장된 모델 가중치 경로 (기본값: 'model_weights.pt')
여기서는 기본값이 model_weights.pt인데 위에서는 saved_model.pth네요?

1. 주석은 큰 문제 없지만 나중에 시간 날때 수정하는게 좋을 것 같습니다.
2. 생각해보니 backend에서 이 모델 돌리려면 saved_model.pth 파일이 있어야 할 것 같네요. 따로 공유해주시거나 깃허브에 올려도 되는 파일이라고 판단되면 깃허브에 올려서 공유해주시면 될 것 같습니다.

2024-11-30 13:20 UTC, bluelemon61 commented on ai_web_pytorch/review_model.py
> +        model_path (str): 저장된 모델 가중치 경로 (기본값: 'model_weights.pt')
모델파일은 너무 커서 깃헙에 안올라간다고 하더라구
Notion에 드라이브 링크 있어서 고걸로 받아야함니닷

2024-11-30 13:22 UTC, JakeFRCSE commented on ai_web_pytorch/review_model.py
> +        model_path (str): 저장된 모델 가중치 경로 (기본값: 'model_weights.pt')
아하 알겠습니다 바로 resolve conversation 하겠습니다

2024-12-01 04:57 UTC, sanghunii commented on ai_web_pytorch/review_model.py
> +        model_path (str): 저장된 모델 가중치 경로 (기본값: 'model_weights.pt')
오늘 Torch모델이랑 back연결해서 잘 돌아가는지 확인해 보겠습니다 ~_~

2024-12-02 03:17 UTC, merged

2024-12-05 15:32 UTC, bluelemon61 commented
close #8